[package]
name = "syntastic"
version = "0.1.0"
authors = ["Sage Mitchell <dev@mx00s.com>"]
edition = "2018"
description = "Generic abstract syntax representation"
repository = "https://github.com/mx00s/syntastic"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
